# This is a basic workflow to help you get started with Actions

name: Frontend Build Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ draft ]
  pull_request:
    branches: [ draft ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      working-Directory: ./frontend
    strategy:
          matrix:
            node-version: [ 12.x ]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a set of commands using the runners shell
      - name: Run Dependecy Installation
        run: |
          npm install
        working-directory: ${{ env.working-directory }}
        
      - name: Build App
        run: |
          npm run build
        working-directory: ${{ env.working-directory }}
